# Generated by Django 3.1.5 on 2021-01-12 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgebase', '0004_auto_20210111_1741'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('func_area', models.CharField(max_length=80, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='area',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
